name: yemen_project
description: "Yemen Comprehensive Market"
publish_to: 'none'
version: 1.0.9+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  url_launcher: ^6.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7

dev_dependencies:
  url_launcher: ^6.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
